### ISSUE TITLE
[chore] chat, review 모델 구현

### ISSUE THREAD

**Issue by jun02160** [SOPT-32ND-APP4-Karrot/Carrot-SERVER#2]
## 📝 Description

1. 로컬 환경에서 DB 테이블 생성 및 데이터 제대로 들어가는지 확인한다.
2. 이후, RDS를 연결하여 DB를 공유하고, 테스트를 위한 더미 데이터를 삽입한다. 
3. java 코드로 엔티티를 설계한 후, 적절한 연관관계 매핑과 메소드를 구현한다.

## ✅ TODO

- [x]  JPA를 이용한 DB 테이블 생성 테스트 -> local에서 test
- [x]  ChatMessage, ChatRoom 구현 및 연관관계 매핑
- [x]  Review, ReviewContent 구현 및 연관관계 매핑
- [x] 연관관계 메소드 구현
