### ISSUE TITLE
[refactor] 예외처리 추가 및 코드 리팩토링 

### ISSUE THREAD

**Issue by jun02160** [SOPT-32ND-APP4-Karrot/Carrot-SERVER#21]
## 📝 Description

1. 전반적인 코드 리팩토링
2. RDS 연결하여 뷰에 따른 더미데이터 삽입

## ✅ TODO

- [ ] 불필요한 import문, 주석 제거
- [ ] 예외처리 조건 깐깐하게 더 추가하기
- [ ] API 명세서와 필드명 완전히 동일한지 체크
- [ ] 전반적인 코드 리팩토링
