### ISSUE TITLE
[feat] 채팅_채팅하기

### ISSUE THREAD

**Issue by jun02160** [SOPT-32ND-APP4-Karrot/Carrot-SERVER#6]
## 📝 Description

1. ChatRoom, ChatMessage에 관한 ResponseDTO 생성
2. ChatRoom, ChatMessage 엔티티에 관한 비즈니스 로직, 컨트롤러 구현

## ✅ TODO

- [x]  GET 방식의 채팅 관련 API 구현
- [ ] 가능하면 CRUD 모두 구현해서 DB 테스트 해보기!
- [x] 예외처리 적용
- [x] 응답 형식 통일
